apiVersion: operator.github.com/v1
kind: Deployer
metadata:
  labels:
    app.kubernetes.io/name: deployer
    app.kubernetes.io/instance: deployer-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: deployer-sample
spec:
  # TODO(user): Add fields here
